<script setup lang="ts">
import ProfileCard from "~/components/ProfileCard.vue";
import ErrorState from "~/components/ErrorState.vue";
import SkeletonCard from "~/components/SkeletonCard.vue";
import { useApiClient } from "~/composables/useApiClient";
import type { Profile } from "~/types/profile";

useSeo(
  "Home · Random Profiles",
  "Browse a gallery of random profiles generated by our local API."
);

const { listProfiles } = useApiClient();
const { data, error, status, refresh } = await useAsyncData<Profile[]>(
  "home-profiles",
  () => listProfiles(12),
  { server: true, lazy: true }
);
</script>

<template>
  <section aria-labelledby="home-heading">
    <div class="flex items-center justify-between mb-4">
      <h1 id="home-heading" class="text-2xl font-bold">Discover People</h1>
      <button
        @click="refresh()"
        class="px-3 py-1.5 rounded bg-indigo-600 text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
      >
        Refresh
      </button>
    </div>

    <div
      v-if="status === 'pending'"
      class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4"
    >
      <SkeletonCard v-for="i in 8" :key="i" />
    </div>

    <ErrorState v-else-if="error" :message="String(error)" />

    <div
      v-else
      class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4"
    >
      <ProfileCard v-for="p in data" :key="p.id" :profile="p" />
    </div>
  </section>
</template>
